/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota

export type Difficulty = (typeof DifficultyObject)[keyof typeof DifficultyObject];
export type Gamestate = (typeof GamestateObject)[keyof typeof GamestateObject];
export const DifficultyObject = {
    Beginner: "beginner",
    Intermediate: "intermediate",
    Expert: "expert",
} as const;
export const GamestateObject = {
    Playing: "playing",
    Lost: "lost",
    Won: "won",
} as const;
/* tslint:enable */
/* eslint-enable */
