version: "2"
run:
  timeout: 2m
  tests: false
  go: "1.24"
  concurrency: 4
linters:
  default: all
  disable:
    - depguard
    - err113
    - gochecknoglobals
    - godox
    - mnd
    - varnamelen
    - exhaustruct
  settings:
    revive:
      rules:
        - name: var-naming
          arguments:
            - ["ID"]
    staticcheck:
      initialisms: ["Id"]
output:
  show-stats: false
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true
issues:
  uniq-by-line: false
