run:
  timeout: 2m
  tests: false
  go: "1.24"
  concurrency: 4
linters:
  enable-all: true
  disable:
    - depguard
    - varnamelen
    - mnd
    - gochecknoglobals
    - godot
    - exhaustruct
    - ireturn
    - err113
    - godox
    - tenv
output:
  print-issued-lines: true
  print-linter-name: true
  show-stats: false
  sort-results: true
issues:
  uniq-by-line: false
linters-settings:
  revive:
    rules:
      - name: var-naming
        arguments:
          - ["ID"]
  stylecheck:
    initialisms: ["Id"]
