run:
  timeout: 2m
  tests: false
  go: '1.22.1'
  concurrency: 4
linters:
  enable-all: true
  disable:
    - execinquery
    - gomnd
    - depguard
    - varnamelen
    - mnd
    - gochecknoglobals
    - godot
    - exportloopref
    - exhaustruct
    - ireturn
    - err113
    - godox
output:
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  show-stats: false
  sort-results: true
linters-settings:
  revive:
    rules:
      - name: var-naming
        arguments:
          - ["ID"]
  stylecheck:
    initialisms: ["Id"]