/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota

export type Movetype = (typeof MovetypeObject)[keyof typeof MovetypeObject];
export const MovetypeObject = {
    Open: "open",
    Flag: "flag",
    Chord: "chord",
} as const;
/* tslint:enable */
/* eslint-enable */
