/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-expect-error

// @ts-expect-error
import {
  apiClientProxifier,
  type BaseRequestBuilder,
  type KeysToExcludeForNavigationMetadata,
  type NavigationMetadata,
  type ParseNodeFactoryRegistry,
  type RequestAdapter,
  type SerializationWriterFactoryRegistry,
} from "@microsoft/kiota-abstractions";
// @ts-expect-error
import {
  FormParseNodeFactory,
  FormSerializationWriterFactory,
} from "@microsoft/kiota-serialization-form";
// @ts-expect-error
import {
  JsonParseNodeFactory,
  JsonSerializationWriterFactory,
} from "@microsoft/kiota-serialization-json";
// @ts-expect-error
import { MultipartSerializationWriterFactory } from "@microsoft/kiota-serialization-multipart";
// @ts-expect-error
import {
  TextParseNodeFactory,
  TextSerializationWriterFactory,
} from "@microsoft/kiota-serialization-text";
import {
  type MatchRequestBuilder,
  MatchRequestBuilderNavigationMetadata,
  MatchRequestBuilderRequestsMetadata,
} from "./match/index.js";

/**
 * Instantiates a new {@link MinesClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-expect-error
export function createMinesClient(requestAdapter: RequestAdapter) {
  if (requestAdapter === undefined) {
    throw new Error("requestAdapter cannot be undefined");
  }
  const serializationWriterFactory =
    requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
  const parseNodeFactoryRegistry =
    requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
  const backingStoreFactory = requestAdapter.getBackingStoreFactory();

  if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
    parseNodeFactoryRegistry.registerDefaultDeserializer(
      JsonParseNodeFactory,
      backingStoreFactory,
    );
    parseNodeFactoryRegistry.registerDefaultDeserializer(
      TextParseNodeFactory,
      backingStoreFactory,
    );
    parseNodeFactoryRegistry.registerDefaultDeserializer(
      FormParseNodeFactory,
      backingStoreFactory,
    );
  }

  if (serializationWriterFactory.registerDefaultSerializer) {
    serializationWriterFactory.registerDefaultSerializer(
      JsonSerializationWriterFactory,
    );
    serializationWriterFactory.registerDefaultSerializer(
      TextSerializationWriterFactory,
    );
    serializationWriterFactory.registerDefaultSerializer(
      FormSerializationWriterFactory,
    );
    serializationWriterFactory.registerDefaultSerializer(
      MultipartSerializationWriterFactory,
    );
  }

  const pathParameters: Record<string, unknown> = {
    baseurl: requestAdapter.baseUrl,
  };
  return apiClientProxifier<MinesClient>(
    requestAdapter,
    pathParameters,
    MinesClientNavigationMetadata,
    undefined,
  );
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface MinesClient extends BaseRequestBuilder<MinesClient> {
  /**
   * The match property
   */
  get match(): MatchRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MinesClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MinesClientNavigationMetadata: Record<
  Exclude<keyof MinesClient, KeysToExcludeForNavigationMetadata>,
  NavigationMetadata
> = {
  match: {
    requestsMetadata: MatchRequestBuilderRequestsMetadata,
    navigationMetadata: MatchRequestBuilderNavigationMetadata,
  },
};
/* tslint:enable */
/* eslint-enable */
