/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-expect-error

// @ts-expect-error
import type {
  BaseRequestBuilder,
  KeysToExcludeForNavigationMetadata,
  NavigationMetadata,
  Parsable,
  ParsableFactory,
  RequestConfiguration,
  RequestInformation,
  RequestsMetadata,
} from "@microsoft/kiota-abstractions";
import { type NewGameDto, serializeNewGameDto } from "../models/req/index.js";
// @ts-expect-error
import {
  createMatchstateDtoFromDiscriminatorValue,
  type MatchstateDto,
  serializeMatchstateDto,
} from "../models/res/index.js";
// @ts-expect-error
import {
  type WithMatchItemRequestBuilder,
  WithMatchItemRequestBuilderNavigationMetadata,
  WithMatchItemRequestBuilderRequestsMetadata,
} from "./item/index.js";

/**
 * Builds and executes requests for operations under /match
 */
export interface MatchRequestBuilder
  extends BaseRequestBuilder<MatchRequestBuilder> {
  /**
   * Gets an item from the ApiSdk.match.item collection
   * @param matchId Match identifier
   * @returns {WithMatchItemRequestBuilder}
   */
  byMatchId(matchId: string): WithMatchItemRequestBuilder;
  /**
   * Starts a new Match that will last roughly 2h
   * @param body The request body
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<MatchstateDto>}
   */
  post(
    body: NewGameDto,
    requestConfiguration?: RequestConfiguration<object> | undefined,
  ): Promise<MatchstateDto | undefined>;
  /**
   * Starts a new Match that will last roughly 2h
   * @param body The request body
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toPostRequestInformation(
    body: NewGameDto,
    requestConfiguration?: RequestConfiguration<object> | undefined,
  ): RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MatchRequestBuilderUriTemplate = "{+baseurl}/match";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MatchRequestBuilderNavigationMetadata: Record<
  Exclude<keyof MatchRequestBuilder, KeysToExcludeForNavigationMetadata>,
  NavigationMetadata
> = {
  byMatchId: {
    requestsMetadata: WithMatchItemRequestBuilderRequestsMetadata,
    navigationMetadata: WithMatchItemRequestBuilderNavigationMetadata,
    pathParametersMappings: ["matchId"],
  },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const MatchRequestBuilderRequestsMetadata: RequestsMetadata = {
  post: {
    uriTemplate: MatchRequestBuilderUriTemplate,
    responseBodyContentType: "application/json",
    adapterMethodName: "send",
    responseBodyFactory: createMatchstateDtoFromDiscriminatorValue,
    requestBodyContentType: "application/json",
    requestBodySerializer: serializeNewGameDto,
    requestInformationContentSetMethod: "setContentFromParsable",
  },
};
/* tslint:enable */
/* eslint-enable */
