/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-expect-error

// @ts-expect-error
import type {
  AdditionalDataHolder,
  Parsable,
  ParseNode,
  SerializationWriter,
} from "@microsoft/kiota-abstractions";
import { type Difficulty, DifficultyObject } from "../game/index.js";
// @ts-expect-error
import { type Movetype, MovetypeObject } from "../matchmaking/index.js";

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MoveDto}
 */
// @ts-expect-error
export function createMoveDtoFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoMoveDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {NewGameDto}
 */
// @ts-expect-error
export function createNewGameDtoFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoNewGameDto;
}
/**
 * The deserialization information for the current model
 * @param MoveDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-expect-error
export function deserializeIntoMoveDto(
  moveDto: Partial<MoveDto> | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    type: (n) => {
      moveDto.type = n.getEnumValue<Movetype>(MovetypeObject);
    },
    x: (n) => {
      moveDto.x = n.getNumberValue();
    },
    y: (n) => {
      moveDto.y = n.getNumberValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @param NewGameDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-expect-error
export function deserializeIntoNewGameDto(
  newGameDto: Partial<NewGameDto> | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    difficulty: (n) => {
      newGameDto.difficulty = n.getEnumValue<Difficulty>(DifficultyObject);
    },
  };
}
export interface MoveDto extends AdditionalDataHolder, Parsable {
  /**
   * The type property
   */
  type?: Movetype | null;
  /**
   * The x property
   */
  x?: number | null;
  /**
   * The y property
   */
  y?: number | null;
}
export interface NewGameDto extends AdditionalDataHolder, Parsable {
  /**
   * The difficulty property
   */
  difficulty?: Difficulty | null;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MoveDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-expect-error
export function serializeMoveDto(
  writer: SerializationWriter,
  moveDto: Partial<MoveDto> | undefined | null = {},
  isSerializingDerivedType: boolean = false,
): void {
  if (!moveDto || isSerializingDerivedType) {
    return;
  }
  writer.writeEnumValue<Movetype>("type", moveDto.type);
  writer.writeNumberValue("x", moveDto.x);
  writer.writeNumberValue("y", moveDto.y);
  writer.writeAdditionalData(moveDto.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param NewGameDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-expect-error
export function serializeNewGameDto(
  writer: SerializationWriter,
  newGameDto: Partial<NewGameDto> | undefined | null = {},
  isSerializingDerivedType: boolean = false,
): void {
  if (!newGameDto || isSerializingDerivedType) {
    return;
  }
  writer.writeEnumValue<Difficulty>("difficulty", newGameDto.difficulty);
  writer.writeAdditionalData(newGameDto.additionalData);
}
/* tslint:enable */
/* eslint-enable */
