/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-expect-error

// @ts-expect-error
import type {
  BaseRequestBuilder,
  Parsable,
  ParsableFactory,
  RequestConfiguration,
  RequestInformation,
  RequestsMetadata,
} from "@microsoft/kiota-abstractions";
import { type MoveDto, serializeMoveDto } from "../../../models/req/index.js";
// @ts-expect-error
import {
  createMatchstateDtoFromDiscriminatorValue,
  type MatchstateDto,
  serializeMatchstateDto,
} from "../../../models/res/index.js";

/**
 * Builds and executes requests for operations under /match/{matchId}/move
 */
export interface MoveRequestBuilder
  extends BaseRequestBuilder<MoveRequestBuilder> {
  /**
   * Applies a Move to an existing Match
   * @param body The request body
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<MatchstateDto>}
   */
  post(
    body: MoveDto,
    requestConfiguration?: RequestConfiguration<object> | undefined,
  ): Promise<MatchstateDto | undefined>;
  /**
   * Applies a Move to an existing Match
   * @param body The request body
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toPostRequestInformation(
    body: MoveDto,
    requestConfiguration?: RequestConfiguration<object> | undefined,
  ): RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MoveRequestBuilderUriTemplate = "{+baseurl}/match/{matchId}/move";
/**
 * Metadata for all the requests in the request builder.
 */
export const MoveRequestBuilderRequestsMetadata: RequestsMetadata = {
  post: {
    uriTemplate: MoveRequestBuilderUriTemplate,
    responseBodyContentType: "application/json",
    adapterMethodName: "send",
    responseBodyFactory: createMatchstateDtoFromDiscriminatorValue,
    requestBodyContentType: "application/json",
    requestBodySerializer: serializeMoveDto,
    requestInformationContentSetMethod: "setContentFromParsable",
  },
};
/* tslint:enable */
/* eslint-enable */
