/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMatchstateDtoFromDiscriminatorValue, type MatchstateDto } from '../../models/res/index.js';
// @ts-ignore
import { MoveRequestBuilderRequestsMetadata, type MoveRequestBuilder } from './move/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /match/{matchId}
 */
export interface WithMatchItemRequestBuilder extends BaseRequestBuilder<WithMatchItemRequestBuilder> {
    /**
     * The move property
     */
    get move(): MoveRequestBuilder;
    /**
     * Gets a Match with the identifier specified
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MatchstateDto>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MatchstateDto | undefined>;
    /**
     * Gets a Match with the identifier specified
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithMatchItemRequestBuilderUriTemplate = "{+baseurl}/match/{matchId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithMatchItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithMatchItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    move: {
        requestsMetadata: MoveRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithMatchItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithMatchItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMatchstateDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
